/**
 * Workflow Runner
 *
 * This module demonstrates how multi‑agent workflows could be executed
 * concurrently. It leverages the `workerPool` helper to control the number
 * of simultaneously running tasks and uses the plan generated by the
 * orchestrator to determine execution order. Because many Flynn agents
 * operate via remote API calls, running them concurrently can significantly
 * reduce total latency when dependencies allow.【273674145530292†L351-L359】
 *
 * Note: This runner is illustrative and is not wired into the existing
 * CLI. Integrate it in your application code as needed.
 */

import { runTasksInPool, runTasksSequentially } from "./workerPool.js";

// Define the type for an agent step (aligns with orchestrate.ts)
export interface AgentStep {
  id: string;
  role: string;
  subtask: string;
  instructions: string;
  tools: string[];
  workflow: string[];
  constraints: string[];
}

export type ExecutionMode = "sequential" | "parallel" | "mixed";

/**
 * Execute a workflow according to a suggested flow. The function accepts an
 * array of agent steps and runs them either sequentially, fully in parallel,
 * or using a mixed strategy where independent groups are run concurrently up
 * to a given threshold. The actual agent execution is abstracted behind
 * `executeStep` so callers can define how a step should run (e.g., call
 * `executeAgent` from @mastra/core).
 *
 * @param steps - Array of agent steps from the orchestrator
 * @param mode - Execution mode (sequential, parallel, mixed)
 * @param threshold - Maximum number of concurrent tasks in mixed mode
 * @param executeStep - Function to execute a single agent step
 */
export async function runWorkflow(
  steps: AgentStep[],
  mode: ExecutionMode,
  threshold: number,
  executeStep: (step: AgentStep) => Promise<unknown>,
): Promise<unknown[]> {
  const tasks = steps.map((step) => () => executeStep(step));
  if (mode === "sequential") {
    return runTasksSequentially(tasks);
  }
  if (mode === "parallel") {
    return runTasksInPool(tasks, tasks.length);
  }
  // Mixed mode: run up to `threshold` tasks concurrently
  return runTasksInPool(tasks, threshold);
}
